library(shiny)

fluidPage(
  column(width = 2,
         br(),
         sliderInput("p",
                     "Erfolgswahrscheinlichkeit",
                     value = 0.7,
                     min = 0,
                     max = 1,
                     step = 0.01),
         sliderInput("n",
                     "Anzahl an Versuchen",
                     value = 14,
                     min = 1,
                     max = 100,
                     step = 1),
         sliderInput("x",
                     "Anzahl an Erfolgen",
                     value = 5,
                     min = 1,
                     max = 14,
                     step = 1),
         # actionButton("go",
         #              "Go!",
         #              icon = icon("microchip")),
         br(),
         textOutput("dist")
  ),
  column(width = 5,
         br(),
         plotOutput("wahrscheinlichkeitsfunktion")),
  column(width = 5,
         br(),
         plotOutput("verteilungsfunktion"))
)
